### ISSUE TITLE
Duplicate Console Reporter in Figure 4

### ISSUE THREAD

**Issue by ralphite** [delftswa2017/desosa2017#55]
Console Reporter appears twice in Figure 4. Diagram displaying the package structure of Yarn.

Could you update this image? BTW, great write up..learnt a lot!

**Comment by TimvdLippe** [comment]
Oh great catch! @Keraito do you have the original file lying around somewhere?

**Comment by Keraito** [comment]
Just opened a PR for it, see #56. Thanks for the catch!
